name = "navsphere"
compatibility_date = "2024-11-11"
compatibility_flags = ["nodejs_compat"]
pages_build_output_dir = ".vercel/output/static"

[env.production.vars]
GITHUB_CLIENT_ID = "Ov23li32Kumarkoi17ks"
GITHUB_OWNER = "epiphany14"
GITHUB_REPO = "Navtabs"
GITHUB_BRANCH = "main"
NEXTAUTH_URL = "https://navtabs.pages.dev/api/auth"
NEXT_PUBLIC_API_URL="https://navtabs.pages.dev"

